spring:
  application:
    name: 'user-service-api'
  data:
    mongodb:
      uri: "mongodb+srv://helpdesk:mongodb@cluster-helpdesk.rjtoy.mongodb.net/helpdeskdb?retryWrites=true&w=majority&appName=cluster-helpdesk"
      auto-index-creation: true
